#version 460

layout (local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, rgba32f) readonly uniform image2D uInput;
layout(set = 0, binding = 1, rgba8) uniform image2D uOutput;

void main() {
    if (gl_GlobalInvocationID.xy != clamp(gl_GlobalInvocationID.xy, ivec2(0), imageSize(uOutput))) return;

    vec4 color = vec4(1.0f);//texture(uInput, texCoord);

    // Do post processing here

    imageStore(uOutput, ivec2(gl_GlobalInvocationID.xy), color);
}