[package]
name = "MeshLoader"
version = "0.1.0"
edition = "2021"

[dependencies]
mvcore = { path = "../../Core" }
mvutils.workspace = true
mvlogger.workspace = true
bytebuffer.workspace = true
serde_json = "1.0.128"