[package]
name = "mvengine_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
mvcore = { path = "../../Core" }
mvengine_render2d = { path = "../Render2D" }
mvutils.workspace = true
mvlogger.workspace = true

gpu-alloc.workspace = true
shaderc.workspace = true
log.workspace = true